### ISSUE TITLE
Add wordlists for other languages

### ISSUE THREAD

**Issue by itai192** [Meshiest/outofcontext#10]
Can you add more languages to your game, wurderer, it's a good game but we can't play it because we speak other languages

**Comment by Meshiest** [comment]
the wurderer word list for English consists of the 3000-8000 most commonly used words (not too obscure and not too easy)

if you can provide me with a sufficiently large list of words, 3000-5000 words, that you and your group find suitable for your language, I can add a dropdown to let users select a word list for Wurderer.

**Comment by itai192** [comment]
thank you I'll try to provide this list for you
