### ISSUE TITLE
Add short alarm bell when it's your turn to do something

### ISSUE THREAD

**Issue by slowdive-** [Meshiest/outofcontext#16]
We like to play ridiculously long rounds of the skribbl game and it's easy to get distracted and miss when it's your turn again to do something. Can there be a setting to enable a short sound or notification (whichever is easier) for the player? Sadly I don't have any experience with Vue.js so I wouldn't know where to start with this.

**Comment by Meshiest** [comment]
I added vibration in places where turns would begin, though it's only effective with on android with certain browsers.

This kind of feature necessitates adding a sort of settings menu that would reside at the bottom of the screen to replace the dark theme popup. 

I like the idea and I'll see what I can do! I'll also see if I can procure some kind of CC-0 sound that is remotely appealing.

**Comment by Meshiest** [comment]
Here's a few notification sounds I've modified from freesounds, I'm probably going to let the user select whichever one they want.

https://github.com/Meshiest/outofcontext/tree/feat-sounds/res/audio

LMK what you think @slowdive-

**Comment by slowdive-** [comment]
Nice! My favorite one here would probably be ``chime.wav``. ``pluck.wav`` is too short and high-pitched IMO. If you don't want to overwhelm with too much choice I think

* ``bit.wav``
* ``chime.wav``
* ``chord.wav``
* ``ding.wav``
* ``wobble.wav``

are sufficient.

**Comment by Meshiest** [comment]
Thanks, I'll go with these!

**Comment by Meshiest** [comment]
I've finished the feature, will have it live when it's not interrupting anyone's games

**Comment by slowdive-** [comment]
Works like a charm. Thanks for the quick response!
